from app.models.trend import Trend
from app.models.creator import Creator, PlatformPower, AmplifiedTrend
from app.models.region import Region, RegionCategory, RegionTrend, RegionCreator


TRENDS = [
    Trend(
        id=1,
        title="OpenAI Sora",
        slug="openai-sora",
        category="AI",
        engagement=118000,
        velocity=91,
        sentiment=88,
        score=94,
        direction="rocket",
        momentum=[18, 28, 42, 64, 81, 94],
    ),
    Trend(
        id=2,
        title="Tesla Robotaxi",
        slug="tesla-robotaxi",
        category="Tech",
        engagement=87000,
        velocity=73,
        sentiment=76,
        score=82,
        direction="up",
        momentum=[22, 35, 47, 58, 66, 73],
    ),
    Trend(
        id=3,
        title="Crypto Market",
        slug="crypto-market",
        category="Finance",
        engagement=68000,
        velocity=42,
        sentiment=51,
        score=67,
        direction="down",
        momentum=[72, 68, 61, 55, 48, 42],
    ),
    Trend(
        id=4,
        title="iPhone 16 Pro",
        slug="iphone-16-pro",
        category="Tech",
        engagement=110000,
        velocity=86,
        sentiment=90,
        score=92,
        direction="rocket",
        momentum=[31, 44, 59, 73, 84, 92],
    ),
    Trend(
        id=5,
        title="Furiosa",
        slug="furiosa",
        category="Movies",
        engagement=128000,
        velocity=83,
        sentiment=80,
        score=89,
        direction="up",
        momentum=[26, 39, 55, 68, 77, 89],
    ),
]
CREATORS = [
    Creator(
        id=1,
        name="Elon Musk",
        slug="elon-musk",
        handle="@elonmusk",
        reach="2.4M",
        creator_score=96,
        amplification=92,
        momentum=[30, 48, 52, 67, 74, 88, 92, 81, 96],
        platforms=[
            PlatformPower(name="X / Twitter", value=92),
            PlatformPower(name="YouTube", value=71),
            PlatformPower(name="Instagram", value=64),
            PlatformPower(name="News Mentions", value=58),
        ],
        amplified_trends=[
            AmplifiedTrend(title="Tesla Robotaxi", slug="tesla-robotaxi"),
            AmplifiedTrend(title="OpenAI Sora", slug="openai-sora"),
            AmplifiedTrend(title="SpaceX", slug="spacex"),
            AmplifiedTrend(title="AI Video", slug="ai-video"),
        ],
    ),
    Creator(
        id=2,
        name="MrBeast",
        slug="mrbeast",
        handle="@mrbeast",
        reach="1.9M",
        creator_score=92,
        amplification=88,
        momentum=[28, 41, 55, 62, 71, 80, 87, 90, 92],
        platforms=[
            PlatformPower(name="YouTube", value=96),
            PlatformPower(name="X / Twitter", value=74),
            PlatformPower(name="Instagram", value=82),
            PlatformPower(name="TikTok", value=89),
        ],
        amplified_trends=[
            AmplifiedTrend(title="YouTube Shorts", slug="youtube-shorts"),
            AmplifiedTrend(title="Creator Economy", slug="creator-economy"),
            AmplifiedTrend(title="AI Video", slug="ai-video"),
        ],
    ),
    Creator(
        id=3,
        name="Apple",
        slug="apple",
        handle="@apple",
        reach="1.4M",
        creator_score=89,
        amplification=84,
        momentum=[22, 36, 47, 59, 66, 74, 82, 86, 89],
        platforms=[
            PlatformPower(name="News Mentions", value=92),
            PlatformPower(name="X / Twitter", value=81),
            PlatformPower(name="YouTube", value=72),
            PlatformPower(name="Instagram", value=68),
        ],
        amplified_trends=[
            AmplifiedTrend(title="iPhone 16 Pro", slug="iphone-16-pro"),
            AmplifiedTrend(title="Apple Intelligence", slug="apple-intelligence"),
            AmplifiedTrend(title="Vision Pro", slug="vision-pro"),
        ],
    ),
    Creator(
        id=4,
        name="Marvel Studios",
        slug="marvel-studios",
        handle="@marvelstudios",
        reach="1.2M",
        creator_score=87,
        amplification=81,
        momentum=[18, 30, 42, 53, 61, 70, 79, 83, 87],
        platforms=[
            PlatformPower(name="Instagram", value=91),
            PlatformPower(name="YouTube", value=84),
            PlatformPower(name="X / Twitter", value=78),
            PlatformPower(name="News Mentions", value=72),
        ],
        amplified_trends=[
            AmplifiedTrend(title="Furiosa", slug="furiosa"),
            AmplifiedTrend(title="Movie Trailers", slug="movie-trailers"),
            AmplifiedTrend(title="Comic Con", slug="comic-con"),
        ],
    ),
]
REGIONS = [
    Region(
        id=1,
        name="India",
        slug="india",
        score=92,
        sentiment=87,
        velocity=91,
        categories=[
            RegionCategory(name="Technology", value=92),
            RegionCategory(name="Movies", value=84),
            RegionCategory(name="Sports", value=76),
            RegionCategory(name="Finance", value=61),
            RegionCategory(name="Politics", value=54),
        ],
        top_trends=[
            RegionTrend(title="OpenAI Sora", slug="openai-sora"),
            RegionTrend(title="Tesla Robotaxi", slug="tesla-robotaxi"),
            RegionTrend(title="Furiosa", slug="furiosa"),
            RegionTrend(title="Crypto Market", slug="crypto-market"),
            RegionTrend(title="iPhone 16 Pro", slug="iphone-16-pro"),
        ],
        creators=[
            RegionCreator(name="Tech Burner", slug="tech-burner", score=94),
            RegionCreator(name="CarryMinati", slug="carryminati", score=88),
            RegionCreator(name="Virat Kohli", slug="virat-kohli", score=86),
            RegionCreator(name="Marvel Studios", slug="marvel-studios", score=82),
        ],
        momentum=[42, 55, 61, 68, 74, 82, 91, 87, 95],
    ),
    Region(
        id=2,
        name="North America",
        slug="north-america",
        score=89,
        sentiment=82,
        velocity=86,
        categories=[
            RegionCategory(name="Technology", value=88),
            RegionCategory(name="Entertainment", value=83),
            RegionCategory(name="Finance", value=78),
            RegionCategory(name="Sports", value=66),
            RegionCategory(name="Politics", value=59),
        ],
        top_trends=[
            RegionTrend(title="Tesla Robotaxi", slug="tesla-robotaxi"),
            RegionTrend(title="OpenAI Sora", slug="openai-sora"),
            RegionTrend(title="Crypto Market", slug="crypto-market"),
            RegionTrend(title="iPhone 16 Pro", slug="iphone-16-pro"),
        ],
        creators=[
            RegionCreator(name="Elon Musk", slug="elon-musk", score=96),
            RegionCreator(name="MrBeast", slug="mrbeast", score=92),
            RegionCreator(name="Apple", slug="apple", score=89),
        ],
        momentum=[38, 49, 57, 63, 70, 79, 86, 84, 89],
    ),
    Region(
        id=3,
        name="Europe",
        slug="europe",
        score=84,
        sentiment=79,
        velocity=81,
        categories=[
            RegionCategory(name="Technology", value=81),
            RegionCategory(name="Movies", value=78),
            RegionCategory(name="Finance", value=73),
            RegionCategory(name="Gaming", value=69),
            RegionCategory(name="Politics", value=62),
        ],
        top_trends=[
            RegionTrend(title="OpenAI Sora", slug="openai-sora"),
            RegionTrend(title="Furiosa", slug="furiosa"),
            RegionTrend(title="Tesla Robotaxi", slug="tesla-robotaxi"),
        ],
        creators=[
            RegionCreator(name="The Verge", slug="the-verge", score=84),
            RegionCreator(name="Marvel Studios", slug="marvel-studios", score=82),
        ],
        momentum=[35, 44, 52, 60, 68, 73, 79, 81, 84],
    ),
    Region(
        id=4,
        name="Asia",
        slug="asia",
        score=88,
        sentiment=83,
        velocity=85,
        categories=[
            RegionCategory(name="Technology", value=89),
            RegionCategory(name="Gaming", value=82),
            RegionCategory(name="Movies", value=75),
            RegionCategory(name="Finance", value=67),
            RegionCategory(name="Sports", value=64),
        ],
        top_trends=[
            RegionTrend(title="OpenAI Sora", slug="openai-sora"),
            RegionTrend(title="iPhone 16 Pro", slug="iphone-16-pro"),
            RegionTrend(title="Tesla Robotaxi", slug="tesla-robotaxi"),
        ],
        creators=[
            RegionCreator(name="Apple", slug="apple", score=89),
            RegionCreator(name="MrBeast", slug="mrbeast", score=86),
        ],
        momentum=[39, 50, 58, 66, 72, 80, 85, 87, 88],
    ),
]