import { Trend } from "@/types/trend";

export const trendingData: Trend[] = [
  {
    id: 1,
    title: "Furiosa",
    category: "Movies",
    engagement: 128000,
    velocity: 92,
    sentiment: 84,
    direction: "rocket",
    score: 92,
  },
  {
    id: 2,
    title: "iPhone 16 Pro",
    category: "Tech",
    engagement: 110000,
    velocity: 88,
    sentiment: 91,
    direction: "rocket",
    score: 91,
  },
  {
    id: 3,
    title: "WWERaw",
    category: "Sports",
    engagement: 92000,
    velocity: 74,
    sentiment: 80,
    direction: "up",
    score: 78,
  },
  {
    id: 4,
    title: "Tesla Robotaxi",
    category: "Tech",
    engagement: 87000,
    velocity: 69,
    sentiment: 66,
    direction: "up",
    score: 73,
  },
  {
    id: 5,
    title: "OpenAI Sora",
    category: "AI",
    engagement: 118000,
    velocity: 94,
    sentiment: 89,
    direction: "rocket",
    score: 94,
  },
  {
    id: 6,
    title: "Crypto Market",
    category: "Finance",
    engagement: 68000,
    velocity: 42,
    sentiment: 48,
    direction: "down",
    score: 61,
  },
];